### ISSUE TITLE
`or`-ed license check breaks on licenses with "or" in the name

### ISSUE THREAD

**Issue by MartijnVdS** [dhatim/python-license-check#101]
The `or`-ed license check, added in https://github.com/dhatim/python-license-check/pull/100 blindly splits the license name on the word "or".

This breaks the license check for projects like `psycopg2` which has a license of `GNU Library or Lesser General Public License (LGPL)` (this gets turned into `["GNU Library", "Lesser General Public License (LGPL)"]` by the `get_license_names` function).

**Comment by ochedru** [comment]
Oops. Reverting.

**Comment by thehale** [comment]
@MartijnVdS Thanks for identifying this issue.

However, I'm concerned that a patch version was used to revert #100, which is itself a breaking change. I sympathize with the criticism that the current `or` split is too broad, but an immediate revert disregards the `or`-split's value in resolving the issue of combinatorial explosion of multiple licenses for most projects.

Surely a more productive fix would have been to add a test for `GNU Library or Lesser General Public License (LGPL)`, then add it to a whitelist of licenses which would not be split by the character sequence `or`. Such an approach would satisfy both needs without too much difficulty.

**Comment by thehale** [comment]
Based on the [actions run](https://github.com/CERT-Polska/Artemis/actions/runs/3823165935/jobs/6511647204) prompting this issue, it appears that @MartijnVdS would also appreciate having `GNU Lesser General Public License v2 or later (LGPLv2+)` in that whitelist.

**Comment by MartijnVdS** [comment]
Reading the standard, it only specifies `OR` in capital letters. Maybe not matching lowercase `or` would do the trick?

**Comment by thehale** [comment]
> Maybe not matching lowercase `or` would do the trick?

That could work. The existing code normalizes the casing to lowercase before checking licenses, but the ` OR ` split* could happen before that normalization occurs.

* Note the spaces surrounding OR.

**Comment by thehale** [comment]
@MartijnVdS I've opened a new PR (#104) which handles the situation you raised. Do you have any concerns with the tests/implementation there?
