### ISSUE TITLE
parameters should be optional and have default implicit values

### ISSUE THREAD

**Issue by ssbarnea** [dhatim/python-license-check#13]
There is no need to force user to add `-r requirements.txt` as this should be taken as default value unless someone defines it.

Same applies for the `-s license_strategy.ini`, which should be assumed to be `license_strategy.ini`. I would personally prefer a hidden file but I see you already picked this.

**Comment by ochedru** [comment]
I agree. We could also use dot files in priority if available. Do you have a PR for this?

**Comment by ticdenis** [comment]
This can be closed because it has already been done.
