### ISSUE TITLE
allow liccheck to be used as a pre-commit hook

### ISSUE THREAD

**Issue by ssbarnea** [dhatim/python-license-check#14]
Enabling liccheck as a pre-commit hook can be done by just adding simple yaml file in the root of the repository which declares the hook so users can use it.

See https://github.com/pre-commit/pre-commit/blob/master/.pre-commit-hooks.yaml

I may make a pull request to add if you want, it is very easy.

**Comment by ochedru** [comment]
Sure, please go ahead and submit a PR.

**Comment by ssbarnea** [comment]
@ochedru I will do this as soon #12 is fixed and included in a release (tag), as this was a requirement for implementing it. I already have the code in my fork but I am waiting for the release to make the PR, it has to be after as pre-commit is always pointing to a release tag.

**Comment by ochedru** [comment]
Please go ahead: I just released 0.3.1 (0.3.0 was good also but had a problem with Travis deploying multiple times to PyPI - fixed with `skip_existing`).

**Comment by abompard** [comment]
Hey @ssbarnea, I'm considering using pre-commit and would like to integrate liccheck with it, are you still willing to submit your hook? Thanks.

**Comment by bagerard** [comment]
This would be a great addition and will also increase the adoption of this library as pre-commit is getting really popular :+1:
