### ISSUE TITLE
whitelisting packages across versions

### ISSUE THREAD

**Issue by larsrinn** [dhatim/python-license-check#26]
Hey, 

this is a great package, it just enriched our CI pipeline :)

Is it possible to whitelist packages without pinning them to specific versions? I presumed:

```
[Authorized Packages]
uuid: "*"
```

or

```
[Authorized Packages]
uuid: "<1.5"
```

but this wasn't working...

**Comment by ochedru** [comment]
I agree this is too restrictive. This should be quite straightforward to extend the version check in the `check_package()` function with e.g. [python-semver](https://python-semver.readthedocs.io/en/latest/index.html). I'll try to put it together into a PR.
