### ISSUE TITLE
liccheck 0.3.11 installation is broken

### ISSUE THREAD

**Issue by westphahl** [dhatim/python-license-check#29]
It seems the installation of liccheck 0.3.11 is broken:

```
$ pip install liccheck                                                                                                                                                                       ~/tmp/liccheck {#}
Collecting liccheck
  Downloading https://files.pythonhosted.org/packages/91/a7/83118d3ba708ebdf29c6bdd7a593d7297311492fe7ca63854ae0c8cbff20/liccheck-0.3.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kdjtfgh6/liccheck/setup.py", line 20, in <module>
        with open(path.join(here, 'requirements.txt'), encoding='utf-8') as f:
      File "/usr/lib/python3.7/codecs.py", line 898, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-kdjtfgh6/liccheck/requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-kdjtfgh6/liccheck/
```

**Comment by ochedru** [comment]
Oops. This is a regression introduced by #28. @shakhat, can you please have a look? Meanwhile, I am reverting and release 0.3.12.

**Comment by ochedru** [comment]
@shakhat I revert parsing of (missing) `requirements.txt` and hardcoded `install_requires`. This should do the trick.

**Comment by ochedru** [comment]
0.3.12 is ok. Thank you for your bug report @westphahl!

**Comment by shakhat** [comment]
> Oops. This is a regression introduced by #28. @shakhat, can you please have a look? Meanwhile, I am reverting and release 0.3.12.

I should have added requirements.txt into manifest file... My fault.

So the correct solution is to add MANIFEST.in with the line "include requirements.txt". This instructs dist to put requirements.txt into the build.

@ochedru Would you like me to propose the correct patch?

**Comment by ochedru** [comment]
> @ochedru Would you like me to propose the correct patch?

Sure, go ahead! Thank you.
