### ISSUE TITLE
Read configuration from `pyproject.toml`

### ISSUE THREAD

**Issue by larsrinn** [dhatim/python-license-check#31]
Thanks for your quick "fix" of #26

I have another proposal: It would be great if it wasn't required to add another configuration file but to include a `liccheck` section in the new `pyproject.toml` file ( https://www.python.org/dev/peps/pep-0518/ ), similar to how black is doing it:

* https://black.readthedocs.io/en/stable/pyproject_toml.html
* https://github.com/python/black/blob/1fbf7251ccdb58ba93301622388615633ecc348a/black.py#L210

A sample configuration might look like this:

```toml
[tool.liccheck]
authorized_licenses = [
  "bsd",
  "new bsd",
  "bsd license"
]
unauthorized_licenses = [
  "gpl v3"
]
authorized_packages = [
  "uuid: 1.30"
]
```

What do you think about this? I'll be happy to open a PR for this.

**Comment by ochedru** [comment]
This sounds like a great idea to improve developer experience! (Actually I did not know about PEP-0518 😄.)
Please feel free to submit a PR.

**Comment by NargiT** [comment]
So is this issue still open ?

**Comment by ochedru** [comment]
Releasing version 0.4.1 with PR #32 "as is". Feel free to experiment with it. Thanks.
