### ISSUE TITLE
Add usage mode to support not resolving dependencies

### ISSUE THREAD

**Issue by micahjsmith** [dhatim/python-license-check#43]
I am conceptually trying to use liccheck in a CI job as follows:
```
pipenv lock -r > requirements.txt
liccheck -r requirements.txt
```

However this fails due to #42 because liccheck tries to resolve all dependencies but they have not actually been installed in any virtualenv. It isn't necessary to resolve dependencies here because the requirements file was generated from the lockfile and has pinned dependencies that have already been resolved. Installing a bunch of dependencies is not desired for what should be a lightweight CI job.

Is it possible to add a usage mode to support this, or does liccheck require all the dependencies to be installed?

**Comment by atugushev** [comment]
Hey @micahjsmith,

I've added `--no-deps` in #48. Any feedback/test/review is welcomed.
