### ISSUE TITLE
liccheck vs liccheck2

### ISSUE THREAD

**Issue by MartinThoma** [dhatim/python-license-check#57]
What is the difference between those two:

* https://pypi.org/project/liccheck/
* https://pypi.org/project/liccheck2/

**Comment by ochedru** [comment]
liccheck2 is a fork made to publish a version on pypi before we did it ourselves: https://github.com/graingert/python-license-check. So I guess it is obsolete now.

**Comment by MartinThoma** [comment]
As you are the maintainer, could you delete liccheck2 (or at least write a notice / redirect there, that liccheck should be used)?

**Comment by ochedru** [comment]
I am not the maintainer of liccheck2, @graingert is.

**Comment by graingert** [comment]
liccheck2 has a wheel, I'll make liccheck2 depend on liccheck when it has a wheel
