### ISSUE TITLE
v0.5.0 is tagged but not on PyPI

### ISSUE THREAD

**Issue by joshfriend** [dhatim/python-license-check#61]

**Comment by ochedru** [comment]
Indeed, I don't know what exactly went wrong.
I am currently in the process of migrating the build and release job to Github actions so hopefully a recent version will land shortly on pypi.

**Comment by ochedru** [comment]
I forgot to bump the version in `setup.py`, that's why. 0.5.1 is now available. Thank you for your bug report.
