### ISSUE TITLE
Some trove license classifiers are ignored

### ISSUE THREAD

**Issue by joshfriend** [dhatim/python-license-check#65]
Not all packages have OSI approved licenses, so their metadata wont be found by a search for `Classifier: License :: OSI Approved ::`. 

Here's the list of all standard trove classifiers: https://pypi.org/classifiers/

Seems like the solution would be to stop looking for `OSI Approved` specifically (make that part of the regex optional).

**Comment by joshfriend** [comment]
Sorry for creating so many issues at once, I just had a bunch of separate suggestions for improvements and thought I would throw them out there for feedback. I will probably end up implementing some of the changes myself (like this one).

**Comment by ochedru** [comment]
> Sorry for creating so many issues at once, I just had a bunch of separate suggestions for improvements and thought I would throw them out there for feedback. I will probably end up implementing some of the changes myself (like this one).

You are welcome! Thank you for contributing.
