### ISSUE TITLE
0.5.2 is not installable: ParseVersionError Unable to parse "dev"

### ISSUE THREAD

**Issue by joshfriend** [dhatim/python-license-check#67]
I am using poetry to manage my environment. `poetry install` throws this error:

```
ParseVersionError Unable to parse "dev"
```

#62 seems to be at fault. It works fine in the build pipeline to create the source tarball and upload to pypi, but it is not installable because setup.py still specifies the version as `dev` when installing

**Comment by ochedru** [comment]
Ah, snap. I have to fix the release pipeline. Thanks for reporting this.

**Comment by ochedru** [comment]
0.5.3 should be ok
