### ISSUE TITLE
pyproject configuration is not included in readme

### ISSUE THREAD

**Issue by ssbarnea** [dhatim/python-license-check#72]
When project configuration was added the README was not updated to mention it, making use of it require some digging. Ideally the readme should cover both.

**Comment by aaronsteers** [comment]
@ssbarnea - I'm new to this tool and I'm also using pyproject.toml (poetry). Do you mind listing here the rough steps you took to get this working, and/or any PRs you located where the needed feature(s) were implemented?

Thanks!

**Comment by ticdenis** [comment]
Included on 7.0.0 version.
